<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>id</string>
	</array>
	<key>name</key>
	<string>Iodine</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(case|e(lse|xcept)|for|i(f|n|s(not)?) |r(aise|eturn)|match|try|w(h(en|ile)|ith)|yield)\b</string>
			<key>name</key>
			<string>keyword.control.id</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(c(lass|ontract)|func|global|lambda|s(elf|uper)|trait)\b</string>
			<key>name</key>
			<string>keyword.other.id</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.id</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.id</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.id</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.other.id</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>keyword.other.import.id</string>
			<key>match</key>
			<string>(use)\s+(.*(?:,.*)*)\s+(from)\s+(.*)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(B(igInt|ool|ytes)|Dict|Exception |Float|Int|List|Null|Str(ingBuffer)?|Tuple)\b</string>
			<key>name</key>
			<string>storage.type.id</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(extends|implements)\b</string>
			<key>name</key>
			<string>storage.modifier.id</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>keyword.other.id</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.id</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*(?!\*)</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.id</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*{2}</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.id</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.id</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.id</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>storage.type.id</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>comment.line.id</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(?:\s|\*)+(@[a-z]+)(\s*([*/a-zA-Z]+)\s*(:(\s*[a-zA-Z]+)?)?)?(\s*(?:.*$))?</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[+-]?\d+((\.\d+)|L)?\b</string>
			<key>name</key>
			<string>constant.numeric.id</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[+-]?0x(\d|[a-fA-F])+L?\b</string>
			<key>name</key>
			<string>constant.numeric.id</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.id</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[bfnrt'"\\]</string>
					<key>name</key>
					<string>constant.character.escape.id</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.quoted.double.id</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.id</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[bfnrt'"\\]</string>
					<key>name</key>
					<string>constant.character.escape.id</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.other.id</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.id</string>
	<key>uuid</key>
	<string>3df878a9-a258-4350-87fc-82025f78d6eb</string>
</dict>
</plist>
